---
- hosts: all

  vars_files:
    - default.config.yml
    - vars/python.yml
    - vars/homebrew.yml
    - vars/vscode.yml
    - vars/flags.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]
    - name: setup helper CLI utility
      template:
        src: templates/gordian-rebuild.j2
        dest: /usr/local/bin/gordian-sync
        mode: 0755 # -rwxr-xr-x
        owner: root
        force: yes
      become: yes
      tags: ["xip"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: gordian_jklapacz.mac.homebrew
      tags: ["brew"]
      when: not skip_brew
    - role: geerlingguy.dotfiles
      when: not skip_dotfiles
      tags: ["dotfiles"]
    - role: gordian_jklapacz.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]

  tasks:
    - import_tasks: tasks/ssh.yml
      vars:
        config_dir: "{{ local_home }}/Dropbox/configs"
        ssh_vault: "{{ config_dir }}/ssh_key_vault.yml"
        ssh_templates: "{{ config_dir }}/templates"
        local_home: "{{ lookup('env','HOME') }}"
        local_user: "{{ lookup('env','USER') }}"
      tags: ["ssh"]
      when: not skip_ssh

    - import_tasks: tasks/homebrew.yml
      tags: ["brew"]
      when: not skip_brew

    - import_tasks: tasks/python.yml
      when: not skip_python
      tags: ["python"]

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/terminal.yml
      when: not skip_terminal
      tags: ["terminal"]

    - import_tasks: tasks/dock.yml
      when: not skip_dock
      tags: ["dock"]

    - import_tasks: tasks/osx.yml
      when: not skip_osx
      tags: ["osx"]

    - import_tasks: tasks/vscode.yml
      when: not skip_vscode
      tags: ["vscode"]

    - import_tasks: tasks/remap-keys.yml
      when: not skip_keys
      tags: ["keys"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ["post"]
