---
- name: Update homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: true
  with_items:
    - git
    - svn
  tags:
  - brew

- name: Install fonts
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ homebrew_fonts }}"

- name: check if .zprofile exists
  stat:
    path: "{{ zprofile_path }}"
  register: zprofile_st

- name: create .zprofile
  file:
    path: "{{ zprofile_path }}"
    state: touch
  when: not zprofile_st.stat.exists

- command: xcrun --show-sdk-path
  register: xcrun_cmd
- set_fact:
    xcrun: "{{ xcrun_cmd.stdout }}/usr"

- name: python-specific environment variables
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK python-specific-environments"
    path: "{{ zprofile_path }}"
    block: |
      export PATH="{{ homebrew_prefix }}/bin"
      export PATH="{{ homebrew_extra_paths | join(":") }}:$PATH"
      export LDFLAGS="{{ homebrew_lib | join(" ") }}:{{ xcrun }}/lib"
      export CFLAGS="{{ homebrew_include | join(" ") }}:{{ xcrun }}/include"
      export CPPLAGS="{{ homebrew_include | join(" ") }}:{{ xcrun }}/include"
      export OPENBLAS="{{ homebrew_openblas }}"
      export MACOSX_DEPLOYMENT_TARGET={{ macosx_deployment_target }}
      # export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

      eval "$(pyenv init --path)"
      alias python="python3"
      export PATH="~/.local/bin:$PATH"

