---
- name: Set VSCode config path
  set_fact:
    vscode_config: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
- name: Check if VSCode config path exists
  stat:
    path: "{{ vscode_config }}"
  register: vscode_settings_st

- name: Create config dir
  ansible.builtin.file:
    path: "{{ vscode_config }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory
  when: not vscode_settings_st.stat.exists

- name: Create a default VSCode configuration
  template:
    src: templates/vscode-settings.json.j2
    dest: "{{ vscode_config }}/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Install VSCode Extensions
  block:
    - name: Set vscode executable
      command: which code
      register: vscode_exe

    - name: List extensions
      command: "{{ vscode_exe.stdout }} --list-extensions"
      register: vscode_installed_extensions

    - block:
        - name: Install VSCode extensions
          shell: "{{ vscode_exe.stdout }} --install-extension {{ item }}"
          when: not item in vscode_installed_extensions.stdout_lines
          loop: "{{ vscode_extensions }}"
        - name: Install vim extension
          shell: "{{ vscode_exe.stdout }} --install-extension {{ vim_extension }}"
          when: vim and not vim_extension in vscode_installed_extensions.stdout_lines
      rescue:
        - name: Recover VSCode Extension Installation
          debug:
            msg: "{{ (ansible_failed_result.results|selectattr('failed', 'defined')|first).stderr_lines }}"
  rescue:
    - debug:
        msg: Extension installation failed, likely because `code` is not resolvable
