---
- set_fact:
    vscode_config: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
- stat:
    path: "{{ vscode_config }}"
  register: vscode_settings_st

- name: Create config dir
  ansible.builtin.file:
    path: "{{ vscode_config }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory
  when: not vscode_settings_st.stat.exists

- name: Create a default VSCode configuration
  template:
    src: templates/vscode-settings.json.j2
    dest: "{{ vscode_config }}/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Install VSCode Extensions
  block:
    - name: Set vscode executable
      command: which code
      register: which_vscode

    - set_fact:
        vscode_bin: "{{ which_vscode.stdout }}"

    - name: List extensions
      command: "{{ vscode_bin }} --list-extensions"
      register: vscode_installed_extensions

    - debug:
        var: which_vscode
    - debug:
        var: vscode_installed_extensions

    - block:
        - name: Install VSCode extensions
          shell: code --install-extension {{ item }}
          when: not item in vscode_installed_extensions.stdout_lines
          loop: "{{ vscode_extensions }}"
      rescue:
        - debug:
            msg: "{{ (ansible_failed_result.results|selectattr('failed', 'defined')|first).stderr_lines }}"
  rescue:
    - debug:
        msg: Extension installation failed, likely because `code` is not resolvable
