---
- set_fact:
    vscode_config: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
- stat:
    path: "{{ vscode_config }}" 
  register: vscode_settings_st

- name: Create config dir
  ansible.builtin.file:
    path: "{{ vscode_config }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory
  when: not vscode_settings_st.stat.exists

- name: Create a default VSCode configuration
  template:
    src: templates/vscode-settings.json.j2
    dest: "{{ vscode_config }}/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items:
    - adpyke.vscode-sql-formatter
    - alefragnani.Bookmarks
    - alefragnani.project-manager
    - asvetliakov.vscode-neovim
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - DaltonMenezes.aura-theme
    - dbaeumer.vscode-eslint
    - donjayamanne.python-environment-manager
    - donjayamanne.python-extension-pack
    - DotJoshJohnson.xml
    - dprint.dprint
    - dracula-theme.theme-dracula
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - Equinusocio.vsc-community-material-theme
    - Equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - guyskk.language-cython
    - KevinRose.vsc-python-indent
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - njpwerner.autodocstring
    - patrick91.python-dependencies-vscode
    - PKief.material-icon-theme
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - shakram02.bash-beautify
    - tamasfe.even-better-toml
    - vincaslt.highlight-matching-tag
    - VisualStudioExptTeam.vscodeintellicode
    - wholroyd.jinja
    - yzhang.markdown-all-in-one
    - Boto3.typed
